// GENERATED by scripts/languages/approveSheets.ts alongside data.ts — do not edit.
// Approved language names and aliases → canonical name, for Collection's "About" link.
export const SHEET_NAMES: Record<string, string> = {};
