// Dev-only: samples Natural Earth land (via world-atlas, 110m) onto a 1.5 degree
// grid and writes lib/languages/mapDots.ts. Run with `npm run languages:map`.
// d3-geo, topojson-client and world-atlas are ESM, so they are loaded with
// dynamic import() inside main(). Nothing in app/ or components/ may import them.
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";

const STEP = 1.5;
const LON_MIN = -180;
const LON_MAX = 178.5;
const LAT_MIN = -58.5;
const LAT_MAX = 81;

const round1 = (n: number) => Math.round(n * 10) / 10;

async function main() {
  const { geoContains } = await import("d3-geo");
  const { feature } = await import("topojson-client");
  const require = createRequire(import.meta.url);
  const topo = JSON.parse(
    readFileSync(require.resolve("world-atlas/land-110m.json"), "utf8"),
  );
  const land = feature(topo, topo.objects.land) as unknown as Parameters<
    typeof geoContains
  >[0];

  const dots: [number, number][] = [];
  for (let lat = LAT_MIN; lat <= LAT_MAX + 1e-9; lat += STEP) {
    for (let lon = LON_MIN; lon <= LON_MAX + 1e-9; lon += STEP) {
      const p: [number, number] = [round1(lon), round1(lat)];
      if (geoContains(land, p)) dots.push(p);
    }
  }

  const body = dots.map(([lon, lat]) => `[${lon},${lat}]`).join(",");
  const out = `// GENERATED by scripts/languages/buildMapDots.ts (npm run languages:map). Do not edit.
// Source: Natural Earth land 110m via the world-atlas package (public domain).
// Grid: ${STEP} degree spacing, lon ${LON_MIN}..${LON_MAX}, lat ${LAT_MIN}..${LAT_MAX} (Antarctica skipped).
// Dots are [lon, lat]. ${dots.length} dots.
import type { Dot } from "./mapGeometry";

export const LAND_DOTS: Dot[] = [${body}];
`;
  const target = path.join(process.cwd(), "lib/languages/mapDots.ts");
  writeFileSync(target, out);
  console.log(`Wrote ${dots.length} dots, ${Buffer.byteLength(out)} bytes -> ${target}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
